# -*- coding: utf-8 -*-
"""pandas skill

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UsQ12KsQ00hsqgTdJI8D6XPN3gZXYogr
"""

import pandas as pd
df=pd.read_csv('/content/Supermart Grocery Sales - Retail Analytics Dataset.csv')
# Preview raw data
print("Raw Data Sample:")
print(df.head())

# Quick summary
print(df.info())
print(df.describe())

df_cleaned = df.copy()

def parse_date(x):
    for fmt in ("%m/%d/%Y", "%d-%m-%Y", "%m-%d-%Y"):
        try:
            return pd.to_datetime(x, format=fmt)
        except:
            continue
    return pd.NaT

df_cleaned['Order Date'] = df_cleaned['Order Date'].apply(parse_date)
# Ensure Sales is float
df_cleaned['Sales'] = df_cleaned['Sales'].astype(float)
# Extract Year, Month, Day into new columns
df_cleaned['Order_Year'] = df_cleaned['Order Date'].dt.year
df_cleaned['Order_Month'] = df_cleaned['Order Date'].dt.month
df_cleaned['Order_Day'] = df_cleaned['Order Date'].dt.day

df_cleaned=df_cleaned.drop(['Order ID','Order Date','State'],axis=1)
df_cleaned['Profit_Margin'] = df_cleaned['Profit'] / df_cleaned['Sales']

df_cleaned.head()

import matplotlib.pyplot as plt

#Sales by Category before cleaning
sales_before = df.groupby('Category')['Sales'].sum()

# Sales by Category after cleaning
sales_after = df_cleaned.groupby('Category')['Sales'].sum()

# Compare side by side
fig, ax = plt.subplots(1, 2, figsize=(14,5))
sales_before.plot(kind='bar', ax=ax[0], title="Sales by Category (Before Cleaning)")
sales_after.plot(kind='bar', ax=ax[1], title="Sales by Category (After Cleaning)")
plt.tight_layout()
plt.show()

import seaborn as sns

plt.figure(figsize=(8,5))

# Histogram with better styling
sns.histplot(df_cleaned['Sales'], bins=30, kde=True, color='skyblue')
plt.title("Distribution of Sales", fontsize=14)
plt.xlabel("Sales Amount")
plt.ylabel("Frequency")
# Add legend for clarity
plt.legend(["Sales Distribution", "KDE Curve"])
plt.show()

margin_by_region = df_cleaned.groupby('Region')['Profit_Margin'].mean()

margin_by_region.plot(kind='bar', figsize=(8,5), color='teal', title="Average Profit Margin by Region")
plt.ylabel("Profit Margin")
plt.xlabel("Region")
plt.show()

df_cleaned.to_csv("df_cleaned.csv", index=False)

# CHECK OUTLIERS BY BOX PLOT
import seaborn as sns

# Select only numerical columns
num_cols = df_cleaned.select_dtypes(include=['float64','int64']).columns
plt.figure(figsize=(15, 8))
for i, col in enumerate(num_cols, 1):
    plt.subplot(2, (len(num_cols)+1)//2, i)
    sns.boxplot(y=df_cleaned[col], color="skyblue")
    plt.title(col)

plt.tight_layout()
plt.show()

num_cols = df_cleaned.select_dtypes(include=['float64','int64']).columns
# Calculate skewness for each numerical column
skew_values = df_cleaned[num_cols].skew()

print("Skewness of numerical columns:")
print(skew_values)

import matplotlib.pyplot as plt

# Winsorization using 1st and 99th percentiles
lower, upper = df_cleaned['Profit'].quantile([0.01, 0.99])
df_cleaned['Profit'] = df_cleaned['Profit'].clip(lower, upper)

df_cleaned.head()

df_cleaned=df_cleaned.drop(['Customer Name'],axis=1)

df_cleaned["Discount_Level"] = pd.cut(df_cleaned["Discount"],
                                      bins=[0, 0.1, 0.2, 0.3, 1],
                                      labels=['Low', 'Medium', 'High', 'VeryHigh'])


df_cleaned["Is_Weekend"] = df_cleaned["Order_Day"].apply(lambda x: 1 if x in [6,7] else 0)


df_cleaned["Profit_per_Discount"] = df_cleaned["Profit"] / (df_cleaned["Discount"] + 0.001)


df_cleaned["Season"] = df_cleaned["Order_Month"].apply(
    lambda m: "Winter" if m in [12,1,2] else
              "Spring" if m in [3,4,5] else
              "Summer" if m in [6,7,8] else
              "Fall"
)


df_cleaned["High_Profit"] = (df_cleaned["Profit"] > df_cleaned["Profit"].median()).astype(int)

df_cleaned=df_cleaned.drop(['City','Profit','Profit_Margin'],axis=1)
df_cleaned.head()

cat_cols = ['Category','Sub Category','Region','Season','Discount_Level']

for col in cat_cols:
    freq = df_cleaned[col].value_counts(normalize=True)
    rare_labels = freq[freq < 0.02].index
    df_cleaned[col] = df_cleaned[col].replace(rare_labels, 'Other')

X_cat = pd.get_dummies(df_cleaned[cat_cols], drop_first=True)

num_cols = ['Discount', 'Order_Year', 'Order_Month', 'Order_Day', 'Is_Weekend', 'Profit_per_Discount', 'High_Profit', 'Quarter']
X_num = df_cleaned[num_cols]

X = pd.concat([X_num, X_cat], axis=1)
y = df_cleaned['Sales']

import numpy as np
from sklearn.model_selection import train_test_split, KFold, cross_val_predict
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestRegressor(n_estimators=300, max_depth=15, min_samples_leaf=5, random_state=42)
model.fit(X_train, y_train)

def regression_metrics(y_true, y_pred):
    r2 = r2_score(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_true, y_pred)
    mape = np.mean(np.abs((y_true - y_pred) / (y_true + 1e-6))) * 100
    return {'R2': r2, 'RMSE': rmse, 'MAE': mae, 'MAPE (%)': mape}

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

train_metrics = regression_metrics(y_train, y_train_pred)
test_metrics = regression_metrics(y_test, y_test_pred)

print("Train Metrics:", train_metrics)
print("Test Metrics:", test_metrics)

plt.figure(figsize=(8,6))
plt.scatter(y_test, y_test_pred, alpha=0.5)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--')
plt.xlabel("Actual Sales")
plt.ylabel("Predicted Sales")
plt.title("Actual vs Predicted Sales (Test Set)")
plt.show()

import pandas as pd

# Create a dictionary of results
results = {
    'Metric': ['R²', 'RMSE', 'MAE', 'MAPE (%)'],
    'Train': [train_metrics['R2'], train_metrics['RMSE'], train_metrics['MAE'], train_metrics['MAPE (%)']],
    'Test': [test_metrics['R2'], test_metrics['RMSE'], test_metrics['MAE'], test_metrics['MAPE (%)']],
    'Cross-Validation': [cv_metrics['R2'], cv_metrics['RMSE'], cv_metrics['MAE'], cv_metrics['MAPE (%)']]
}

# Convert to DataFrame
results_df = pd.DataFrame(results)

# Display nicely
print(results_df)

import matplotlib.pyplot as plt

metrics = ['R²','RMSE','MAE','MAPE (%)']
train_vals = results_df['Train']
test_vals = results_df['Test']
cv_vals = results_df['Cross-Validation']

x = np.arange(len(metrics))
width = 0.25

plt.figure(figsize=(10,5))
plt.bar(x - width, train_vals, width, label='Train')
plt.bar(x, test_vals, width, label='Test')
plt.bar(x + width, cv_vals, width, label='Cross-Validation')

plt.xticks(x, metrics)
plt.ylabel('Value')
plt.title('Model Metrics Comparison')
plt.legend()
plt.show()